# Generated by Django 4.0.1 on 2022-04-22 21:45

from django.db import migrations, models
import django.db.models.deletion
import user__app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mob_no', models.CharField(blank=True, help_text='Enter 10 digit mobile number', max_length=10, null=True, unique=True, validators=[user__app.models.validating_mobno])),
            ],
        ),
        migrations.CreateModel(
            name='customer_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user__app.user_model')),
            ],
        ),
    ]
